Nicklason/tf2-automatic

- app/trade.js
- package.json
Fixed a problem where the bot would not make an offer because the items was already trades away
> Items traded away fix

- app/messages.js
> Don’t require you to say that the item you are adding is not autopriced

- app/messages.js
Making it the same as the add command
> Trims update name string to remove whitespace

- app/messages.js
> Peanut Butter

- app/config.js
- app/messages.js
Probs bad code but it works sooooo...
> Whitelist for !removefriends

- app/messages.js
> changed noone to no one

- app/inventory.js
- app/trade.js
- package.json
> Fixed stock limits for chat commands

- app/offer.js
> Removed unused 'opts'

- app/handler-manager.js
https://github.com/Nicklason/tf2-automatic/issues/178
> Stop heartbeat and inventory timers when stopping the bot

- app/handler/commands.js
Trades done in the last 24 hours & total trades recorded.
> Adds !trades command

- app/handler/commands.js
Originally from https://github.com/Nicklason/tf2-automatic/issues/175
> Added command that requests price check

- lib/validator.js
> Changed == to === (strict)

- app/handler/commands.js
Add ability to use !update all=true with intent/min/max/enabled/autoprice as optional parameters
#157
> Update all 

- app/handler-manager.js
- app/handler/commands.js
- app/handler/shutdown.js
- app/handler/trades.js
- app/prices.js
- lib/validator.js
Setting up the pricelist is now a lot faster (https://github.com/Nicklason/tf2-automatic/pull/172)
Added rate command and made bot always value keys using sell price (https://github.com/Nicklason/tf2-automatic/pull/176)
Stop heartbeat and inventory timers when stopping the bot (https://github.com/Nicklason/tf2-automatic/pull/181)
Added trades command (https://github.com/Nicklason/tf2-automatic/pull/182)
Added command that requests price check (https://github.com/Nicklason/tf2-automatic/pull/185)
Added way to update entire pricelist (https://github.com/Nicklason/tf2-automatic/pull/186)
> Merge development into master

- app.js
- app/version-check.js
> Added notify for admins when update is available

- app/handler/trades.js
https://github.com/Nicklason/tf2-automatic/issues/195
> Offer state fix

- app/handler/commands.js
- package-lock.json
- package.json
> Add !avatar & !name commands

- app/handler/commands.js
Trades command now displays the trades made since the beginning of the day.
> ⚡️Improvement to !trades command

- app.js
- app/handler-manager.js
- app/handler/listings.js
- app/handler/shutdown.js
- app/utils/offer/summarize.js
- package-lock.json
- package.json
- Changed how the bot starts and stops
- Always wait for files to be saved when stopping
- Made startup callback tree into a series of async functions (once a step of the startup process finishes it will check if a shutdown was requested)
- Updated bptf-listings module
- Use objects as maps for when creating listings and checking if a listing exists
- Changed how listings are made
- Non-blocking, recursive function, iterates through the pricelist and checks for listings to be created and removed.
> Huge performance improvements for creating listings

- src/app/handler/listings.js
> Change to autobump log.

- src/app/handler/commands.js
Fixed the spelling of "selll" lol.
> Removed literally a single letter

- src/classes/MyHandler.ts
Not really needed, spoke to @Nicklason about this on discord, wasn't sure what exactly would have been the best approach, (remove it entirely, or just remove only the summary)
> Removed second accepted summary

- src/classes/Cart.ts
- src/classes/CartQueue.ts
- src/classes/Commands.ts
- src/classes/MyHandler.ts
- src/classes/Trades.ts
- src/types/modules/steam-tradeoffer-manager/index.d.ts
Added !cancel command which will remove you from the cart queue, cancel sending offer if the offer is already being made, and cancel offers sent by the bot.
> Merge development with master

- LICENSE
- README.md
Fixing some tippos and the license year.
> Fix some tippos

- package-lock.json
- package.json
- src/app.ts
There are some free oss type definitions out there to help you in your project.
I have npm installed them for you.
> Install type definitions via npm install @types/__

- src/lib/extend/offer/getDiff.ts
- src/types/modules/steam-tradeoffer-manager/index.d.ts
Fixes: https://github.com/Nicklason/tf2-automatic/issues/310
> fix problem with getting items dict

- ecosystem.template.json
- src/classes/Cart.ts
- template.env
Much beautiful now.
Lessons learned. Thanks!
> Add back OFFER_MESSAGE option

- src/classes/MyHandler.ts
The bot would decline the trade if the offer contained items not from
TF2.
Fixes: https://github.com/Nicklason/tf2-automatic/issues/346
> src: accept all trades from admins

- ecosystem.template.json
- src/app.ts
Fixes: https://github.com/Nicklason/tf2-automatic/issues/352
> src: fix problem with stopping bot using PM2

- src/classes/MyHandler.ts
- src/classes/Trades.ts
- Added missing log for when declining an offer because the item is not traded by the bot
- Log reason when offer changes ![image](https://user-images.githubusercontent.com/21038945/75900512-4f058800-5e3d-11ea-82d4-01773ba55dee.png)
> Offer reasons

- src/classes/Bot.ts
- src/classes/Handler.ts
- src/classes/MyHandler.ts
- src/classes/Trades.ts
Add notification for partner and admins for offers under review
> Received offer alerts

- src/classes/Pricelist.ts
Change ``soure`` to ``source``
> src: Fix items not getting priced.

- src/classes/Commands.ts
- src/classes/Inventory.ts
Fix problem with not using non tradable backpack expander.  https://github.com/Nicklason/tf2-automatic/issues/355
> src: prioritize non-tradable backpack expanders

- src/classes/Commands.ts
https://github.com/Nicklason/tf2-automatic/issues/373
> src: fix wrong word

- src/lib/extend/item/getSKU.ts
Fixes: https://github.com/Nicklason/tf2-automatic/issues/386
> src: fix problem with detecting killstreak

- src/classes/Trades.ts
Fixes: https://github.com/Nicklason/tf2-automatic/issues/374
> src: fix problem with checking escrow

- src/classes/Commands.ts
this one is stable.
[final](https://user-images.githubusercontent.com/47635037/76625966-40bd1780-6573-11ea-9029-d42ff21ed268.PNG)
> add recorded trades time from first trade made in !trades command

- src/classes/Commands.ts
- src/classes/MyHandler.ts
- src/classes/Pricelist.ts
> Add option to clear pricelist

- src/classes/Bot.ts
- src/classes/Commands.ts
https://github.com/Nicklason/tf2-automatic/issues/369
> src: add message command

- package-lock.json
- package.json
- src/app.ts
- src/classes/Commands.ts
This fix will make name parameters case-insensitive when using admin commands such as add, remove and update.
> remove case sensitivity when searching for items

- src/classes/MyHandler.ts
> fix bot sell items with intent=buy (understock)
